In [88]:
# state,action --> reward

import numpy as np
np.random.seed(42)


In [89]:
boxes = np.array ([[0.2,2,-0.3,-3],
                   [-4,-1,0.3,3],
                   [-2,-0.5,0.6,1]])
num_boxes = 3
num_buttons = 4


In [90]:
def getReward(button):
    x=np.random.randn(1)
    if x > button:
        return 1
    else:
        return -1
    #this is the game

In [91]:
def getRandombox():
    state = np.random.randint(0,num_boxes)
    return state


In [92]:
weights = np.ones([num_boxes,num_buttons])

In [93]:
print weights

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [94]:
def getWeight(state, action):
    return weights[state][action] #built-in

In [95]:
total_episodes = 1000
total_rewards = np.zeros([num_boxes,num_buttons])
i = 0 # loop parameter
lr = 0.001 # Learning rate

In [96]:
while i < total_episodes:
    state = getRandombox()
    action = np.random.randint(0,num_buttons)# training by  getting random action everyloop
    w = getWeight(state, action) #1 weight in the weights array
    
    reward = getReward(boxes[state][action]) #getReward(buttons) but button chosen is depended on state,action in the array
    
    loss =-(np.log(w)*reward) #cost which is related to weight and reward which is to be minimised
    # log func used so that gradual inc for inc in w 
    
    weights[state][action] = weights[state][action]+lr*reward*(1/w) #differentiate loss func for backtracking, in diff rewarrd is indep of w and thus like a constant  hence comes out of the dist
    
    # show-off

    total_rewards[state][action] += reward
    if i%50==0:
        print("rewards for 3 boxes is\n" +str(total_rewards))
    
    i+=1
    
    
    

rewards for 3 boxes is
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]
rewards for 3 boxes is
[[-1. -2. -1.  5.]
 [ 5.  1. -2. -4.]
 [ 4.  4. -3. -3.]]
rewards for 3 boxes is
[[ -6.  -3.  -3.  12.]
 [ 11.   2.  -1. -10.]
 [  5.   9.  -8.  -9.]]
rewards for 3 boxes is
[[ -6.  -4.  -4.  20.]
 [ 16.   7.  -5. -11.]
 [ 11.  11.  -8. -14.]]
rewards for 3 boxes is
[[-11. -10.  -3.  25.]
 [ 19.   6.  -5. -12.]
 [ 15.  11.  -8. -18.]]
rewards for 3 boxes is
[[-15. -17.  -2.  27.]
 [ 23.  10.  -4. -18.]
 [ 19.  13.  -8. -19.]]
rewards for 3 boxes is
[[-17. -22.  -4.  32.]
 [ 29.  12.  -7. -19.]
 [ 21.  14. -10. -22.]]
rewards for 3 boxes is
[[-16. -28.  -2.  38.]
 [ 31.  16.  -5. -20.]
 [ 21.  18.  -8. -26.]]
rewards for 3 boxes is
[[-15. -34.   2.  41.]
 [ 35.  20.  -4. -20.]
 [ 24.  19.  -9. -30.]]
rewards for 3 boxes is
[[-12. -39.   5.  44.]
 [ 38.  23.  -4. -22.]
 [ 27.  23. -14. -30.]]
rewards for 3 boxes is
[[-12. -40.   3.  47.]
 [ 41.  23.   0. -25.]
 [ 34.  24. -15. -33.]]
r

In [97]:
print(weights)

[[ 0.97267238  0.91765238  1.01098003  1.07892439]
 [ 1.07799589  1.04789268  0.9950363   0.92091386]
 [ 1.07054664  1.0354143   0.97574686  0.94132624]]


In [98]:
for a in range(num_boxes):
    print("button- " + str(np.argmax(weights[a])+1) + " for box- "+ str(a+1))

button- 4 for box- 1
button- 1 for box- 2
button- 1 for box- 3
