In [31]:
# assignment- heads n tails - state,action --> rewards 

import numpy as np
import math
np.random.seed(42)
#prime => +1
#not prime => -1


In [32]:
coinsvalues = ([[3,4],
                [11,12],
                [32,31],
                [18,17],
                [42,41]])
num_coins = 5
num_options = 2 #heads(0) or tails(1) => action = 0 or 1

def isprime(n):
    i=2
    k= math.sqrt(n)
    b = False
    while i< k:
        if n%i==0:
            b = True
        i+=1    
    return b        
        
def getReward(valueofchoice):
    #valueofchoice = coinsvalues[state][action] 
     
    if isprime(valueofchoice) == True:
        return 1
    else:
        return -1

In [33]:
def getRandomCoin():
    state = np.random.randint(0,num_coins)
    return state


In [34]:
weights = np.ones([num_coins,num_options]) #{no.of cols, no.of rows}
print weights

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [35]:
def getWeight(state, action):
    return weights[state][action] #built-in

In [36]:
total_episodes = 1000
total_rewards = np.zeros([num_coins,num_options])
i = 0 # loop parameter
lr = 0.001 # Learning rate

In [37]:
while i < total_episodes:
    state = getRandomCoin()
    action = np.random.randint(0,num_options)# training by  getting random action everyloop
    w = getWeight(state, action) #1 weight in the weights array
    
    reward = getReward(coinsvalues[state][action]) #getReward(valueofchoice) but button chosen is depended on state,action in the array
    
    loss =-(np.log(w)*reward) #cost which is related to weight and reward which is to be minimised
    # log func used so that gradual inc for inc in w 
    
    weights[state][action] = weights[state][action]+lr*reward*(1/w) #differentiate loss func for backtracking, in diff rewarrd is indep of w and thus like a constant  hence comes out of the dist
    
    # show-off

    total_rewards[state][action] += reward
    if i%50==0:
        print("rewards :\n" +str(total_rewards))
    
    i+=1
    
    

rewards :
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  0.]]
rewards :
[[-4. -4.]
 [-2.  9.]
 [ 2. -4.]
 [ 6. -8.]
 [ 5. -7.]]
rewards :
[[ -9. -11.]
 [ -5.  10.]
 [ 12.  -7.]
 [ 10. -16.]
 [ 11. -10.]]
rewards :
[[-15. -21.]
 [ -9.  14.]
 [ 17. -13.]
 [ 17. -20.]
 [ 12. -13.]]
rewards :
[[-20. -28.]
 [-14.  18.]
 [ 19. -23.]
 [ 21. -24.]
 [ 17. -17.]]
rewards :
[[-22. -35.]
 [-21.  24.]
 [ 23. -26.]
 [ 23. -30.]
 [ 23. -24.]]
rewards :
[[-27. -39.]
 [-26.  29.]
 [ 26. -31.]
 [ 28. -36.]
 [ 29. -30.]]
rewards :
[[-32. -42.]
 [-31.  32.]
 [ 31. -36.]
 [ 34. -42.]
 [ 37. -34.]]
rewards :
[[-41. -49.]
 [-33.  38.]
 [ 32. -39.]
 [ 40. -47.]
 [ 43. -39.]]
rewards :
[[-48. -58.]
 [-36.  46.]
 [ 39. -39.]
 [ 42. -51.]
 [ 47. -45.]]
rewards :
[[-55. -61.]
 [-43.  52.]
 [ 49. -41.]
 [ 45. -55.]
 [ 48. -52.]]
rewards :
[[-61. -66.]
 [-48.  58.]
 [ 54. -46.]
 [ 53. -58.]
 [ 50. -57.]]
rewards :
[[-65. -69.]
 [-49.  63.]
 [ 65. -49.]
 [ 56. -64.]
 [ 56. -65.]]
rewards :
[[-71. -73.]
 [-59.  6

In [38]:
print(weights)


[[ 0.8809805   0.88888566]
 [ 0.90005846  1.0963996 ]
 [ 1.09731167  0.89894742]
 [ 1.08907546  0.89672122]
 [ 1.09457316  0.89560605]]


In [39]:
print("0-heads and 1-tails")
for a in range(num_coins):
    print("option: " + str(np.argmax(weights[a])+1) + " for coin: "+ str(a+1))
    

0-heads and 1-tails
option: 2 for coin: 1
option: 2 for coin: 2
option: 1 for coin: 3
option: 1 for coin: 4
option: 1 for coin: 5
