In [1]:
import numpy as np
np.random.seed(123)  # for reproducibility
 
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
# Load pre-shuffled MNIST data into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11476992/11490434 [============================>.] - ETA: 0s

In [3]:
print X_train.shape

(60000, 28, 28)


In [4]:
from matplotlib import pyplot as plt
plt.imshow(X_train[0])

In [5]:
# Must explicitly declare a dimension for the depth of the input image
# MNIST images only have a depth of 1, but we must explicitly declare that.

X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)

In [6]:
print X_train.shape

(60000, 1, 28, 28)


In [7]:
# convert our data type to float32 and normalize our data values to the range [0, 1] 
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [8]:
print y_train.shape

(60000,)


In [18]:
# We should have 10 different classes, one for each digit, but it looks like we only have a 1-dimensional array
# Lets see the labels for first 3 samples
print y_train[:20]

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]


In [10]:
#  y_train and y_test data are not split into 10 distinct class labels, but rather are represented as a single array with the class values.

# Convert 1-dimensional class arrays to 10-dimensional class matrices
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

In [11]:
print Y_train.shape

(60000, 10)


In [17]:
print Y_train[:20] # one-hot encoding bitches

[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [23]:
model = Sequential()
 
model.add(Convolution2D(32, 1, 1, activation='relu', input_shape=(1,28,28)))
model.add(Convolution2D(32, 1, 1, activation='relu'))
model.add(MaxPooling2D(pool_size=(1,1)))
model.add(Dropout(0.25))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

/home/pranav/lab1/lib/python2.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (1, 1), activation="relu", input_shape=(1, 28, 28...)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/pranav/lab1/lib/python2.7/site-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (1, 1), activation="relu")`
  after removing the cwd from sys.path.


In [24]:
model.fit(X_train, Y_train, 
          batch_size=32, nb_epoch=10, verbose=1)

/home/pranav/lab1/local/lib/python2.7/site-packages/keras/models.py:852: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/10
60000/60000 [==============================] - 10s - loss: 0.3573 - acc: 0.8906    
Epoch 2/10
60000/60000 [==============================] - 9s - loss: 0.1750 - acc: 0.9474     
Epoch 3/10
60000/60000 [==============================] - 9s - loss: 0.1464 - acc: 0.9557     
Epoch 4/10
60000/60000 [==============================] - 9s - loss: 0.1313 - acc: 0.9610     
Epoch 5/10
60000/60000 [==============================] - 9s - loss: 0.1199 - acc: 0.9636     
Epoch 6/10
60000/60000 [==============================] - 9s - loss: 0.1111 - acc: 0.9664     
Epoch 7/10
60000/60000 [==============================] - 8s - loss: 0.1050 - acc: 0.9679     
Epoch 8/10
60000/60000 [==============================] - 8s - loss: 0.1038 - acc: 0.9683     
Epoch 9/10
60000/60000 [==============================] - 8s - loss: 0.0966 - acc: 0.9701     
Epoch 10/10
60000/60000 [==============================] - 8s - loss: 0.0956 - acc: 0.9700     


In [25]:
score = model.evaluate(X_test, Y_test, verbose=0)

In [26]:
print(score)

[0.064047181318234656, 0.98050000000000004]
