In [12]:
import numpy as np
np.random.seed(42)

In [13]:
boxes = np.array([[0.2,2,-0.3,-3], 
                  [-4,-1,0.3,3], 
                  [-2,-0.5,0.6,1]])
num_boxes = 3
num_buttons = 4


In [14]:
def getReward(button):
    x = np.random.randn(1)
    if x > button:
        return 1
    else:
        return -1

In [15]:
def getRandomBox():
    state = np.random.randint(0,num_boxes)
    return state

In [30]:
weights = np.ones([num_boxes,num_buttons])*100

In [31]:
print(weights)

[[ 100.  100.  100.  100.]
 [ 100.  100.  100.  100.]
 [ 100.  100.  100.  100.]]


In [23]:
def getWeight(state, action):
    return weights[state][action]

In [24]:
total_episodes = 1000
total_rewards = np.zeros([num_boxes,num_buttons])
lr = 0.001

In [25]:
i = 0
while i < total_episodes:
    
    state = getRandomBox()
    
    action = np.random.randint(0,num_buttons)
    
    w = getWeight(state, action)
    
    reward = getReward(boxes[state][action])
    
    loss = - (np.log(w)*reward)
    
    weights[state][action] = weights[state][action] + lr*(reward)*(1/w)
    
    total_rewards[state][action] += reward
    
    if i%50 == 0:
        print("Total reward for each of the "+str(num_boxes)+" boxes : \n"+str(total_rewards))
        
    i+=1

Total reward for each of the 3 boxes : 
[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Total reward for each of the 3 boxes : 
[[-2. -5.  0.  1.]
 [ 7.  1. -6. -4.]
 [ 2.  4. -2. -5.]]
Total reward for each of the 3 boxes : 
[[ -6.  -9.  -1.   4.]
 [  9.   4.  -9. -10.]
 [  9.   6.  -2.  -4.]]
Total reward for each of the 3 boxes : 
[[ -6. -13.   5.  11.]
 [ 12.   7.  -9. -15.]
 [ 14.   6.  -4.  -7.]]
Total reward for each of the 3 boxes : 
[[ -7. -19.   1.  13.]
 [ 15.  13.  -8. -15.]
 [ 19.   7.  -5. -13.]]
Total reward for each of the 3 boxes : 
[[-12. -19.   3.  19.]
 [ 18.  14.  -8. -19.]
 [ 26.  12.  -7. -16.]]
Total reward for each of the 3 boxes : 
[[-13. -20.   9.  22.]
 [ 22.  18.  -8. -24.]
 [ 29.  12.  -7. -19.]]
Total reward for each of the 3 boxes : 
[[-18. -25.   8.  24.]
 [ 27.  19.  -7. -28.]
 [ 30.  13.  -9. -23.]]
Total reward for each of the 3 boxes : 
[[-16. -30.   8.  29.]
 [ 33.  23.  -6. -32.]
 [ 34.  15. -10. -27.]]
Total reward for each of the 3 box

In [29]:
for a in range(num_boxes):
    print("I think that button "+ str(np.argmax(weights[a])+1) + " for the box "+str(a+1)+" is the best")
    if np.argmax(weights[a]) == np.argmin(boxes[a]):
        print("Correct")

I think that button 4 for the box 1 is the best
Correct
I think that button 1 for the box 2 is the best
Correct
I think that button 1 for the box 3 is the best
Correct
